[package]
name = "aoc_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
append-only-vec = "0.1.8"
bytecount = "0.6.9"
colored = "3.0.0"
fastrand = "2.3.0"
itertools = "0.14.0"
rayon = "1.11.0"
regex = "1.12.2"
